INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1,'MEZIANI','Belkacem','1959-02-23','H.DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (13,'DIDOUN','Mohamed','1978-10-06','sidi m hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (14,'MAZOUZ','Abderrezak','1987-03-29','kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (19,'NOURI','Said','1967-12-21','BOUKHLIFA','Béjaïa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (20,'LARBAOUI','Laid','1972-11-11','DOUERA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (25,'TAIBA','Mourad','1986-04-20','rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (34,'GALI','ZERARGA','1992-09-03','Kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (51,'GOTNI','Azeddine','1959-11-02','Bouzaria','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (53,'KOUADI','Samir','1971-04-13','BIRKHADEM','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (57,'TALADJADI','Karim','1969-09-16','DAR EL BEIDA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (58,'TELDJA','Elias','1954-01-07','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (60,'ALLAOUA','Bilal','1983-04-25','BEK','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (62,'ZOURDANI','Samir','1968-10-16','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (65,'KOUDRI','Mohamed','1989-06-29','dar elbida','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (67,'SELMAOUI','Rabia','1964-10-05','HUSSEIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (70,'BENDJILLALI','Mohamed','1969-07-31','DOUIRA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (73,'EL','BIR','1978-05-12','El-Harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (75,'ZERROUNI','Yacine','1974-10-27','sidi m hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (79,'ZEMITI','Hakim','1961-06-28','H. Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (83,'BOUSSAID','Nadir','1983-08-09','Bouzareah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (86,'GACEM','Rachid','1973-11-10','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (96,'AMRANI','Ahcène','1980-12-10','Rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (107,'TAMERIOULT','Mourad','1967-11-21','BAB EL OUED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (111,'BAOUCHE','Rachid','1964-08-12','Bologhine','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (114,'DJENANE','Ali','1956-01-09','AIN BENIAN','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (122,'SAYHI','Ahmed','1976-10-09','MSILA','M Sila');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (129,'BENZAOUCHE','Nabil','1971-03-13','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (131,'CHENFAOUI','Kamel','1975-01-11','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (136,'KHALED','KHODJA','1973-07-16','Bir Mourad Rais','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (138,'NANOUCHE','Djamel','1958-08-12','SIDI MOUSSA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (147,'RENAI','Mourad','1975-01-20','ELHARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (155,'GUEZLANE','Mohammed','1963-01-07','HOUSSIN DAY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (157,'ZEGHRABA','Nour-Eddine','1963-11-20','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (167,'DAOUD','Mohamed','1964-05-27','MAHELMA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (169,'HADJ','BEN','1964-05-31','TAHCHATE','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (175,'LAANANI','Nabil','1975-05-18','DAR EL BEIDA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (177,'IRATNI','Sofiane','1973-05-23','SIDI MHAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (191,'MANSEUR','Hamid','1955-06-02','rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (192,'SAHRAOUI','Youcef','1975-05-12','madania','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (199,'MESSAOUD-SADALLAH','Ammar','1960-02-03','MANSOURAH','B.B.Arréridj');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (210,'DJEMA','Kamel','1957-01-11','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (213,'HAMDI','Lies','1963-01-10','sidi mhamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (215,'ABDELLAOUI','Azzeddine','1974-12-04','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (218,'ALIOUA','Rèda','1978-03-12','Bordj El Kiffane','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (221,'BAHMED','Brahim','1968-09-23','Ain Taya','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (227,'BOUZAMA','Redouane','1985-02-28','ain taya','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (230,'KEDDAR','Abdelkader','1972-06-21','Douera','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (232,'KHECHACHE','Allal','1947-02-07','BOUIRA','Bouira');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (233,'LEKMACHE','Hamid','1972-10-01','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (234,'BELHOUT','Salim','1972-07-10','BEIDA EL BORDJ','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (237,'BOUZID','Belgacem','1959-11-11','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (240,'CHERCHAME','Youcef','1969-03-08','kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (247,'BABOUR','Mohamed','1965-02-01','Casbah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (251,'TOUMI','Messaoud','1981-10-05','H.DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (259,'DJABALI','Badredine','1971-11-10','SIDI MHAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (268,'BOUYAHI','Farid','1976-07-02','bouzareah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (279,'LARBAOUI','Lies','1970-01-27','BEO','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (284,'KHELIF','Ahmed','1956-10-26','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (285,'HAMICI','Zouhir','1974-02-22','Douera','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (287,'OUAAD','Ali','1960-01-21','BORDJ MENAIEL','Boumerdés');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (290,'AIOUAZ','Mohamed','1962-03-05','LION','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (299,'FIOTMANE','Abdelkader','1963-03-04','CASBAH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (301,'DILMI','Mustapha','1956-12-15','IGHIL ALI','Béjaïa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (304,'MOHAMED','CHERIF','1977-09-03','STAOUELI','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (307,'MEDDAHI','Redouane','1976-11-29','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (308,'DAGHEFALI','Said','1976-06-26','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (309,'KIHEL','Lamine','1977-02-06','BOLOGHINE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (314,'DRIF','Mahfoud','1965-05-31','H. Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (315,'SAKHER','Hocine','1960-01-09','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (318,'IDIRI','Mohamed','1965-03-28','El Ksar','Béjaïa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (320,'DINE','Mourad','1975-07-11','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (322,'BOUINOUNE','Nacer','1986-04-26','Cheraga','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (323,'MEGRACHE','Mourad','1973-03-04','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (324,'AZZI','Belkacem','1967-10-04','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (336,'TRAD','Nacer-Eddine','1964-09-26','Mohamed belouzdad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (338,'ZIANE','Mohamed','1951-12-06','BORDJ EL BAHRI','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (339,'FLIH','Arab','1951-03-11','GUENZAT','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (341,'DEMAI','Ahmed','1972-07-10','Bologhine','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (346,'BEKHTI','Abdelghani','1976-05-25','BOLOGHINE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (357,'THAMEUR','Rachid','1972-11-18','Cheraga','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (359,'BENMORSLI','Mohamed','1965-08-29','kasbah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (360,'DAMAS','Rabah','1955-09-02','Alger Centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (375,'SADOUKI','Billal','1987-11-29','Sidi Moussa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (379,'BOULEKHIOUT','Nabil','1973-08-06','ELHARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (382,'BOURAS','Ramdane','1964-01-13','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (384,'HAOULAY','Kamel','1949-02-06','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (401,'AHMED','BENYAHIA','1979-03-30','attaf','Ain Defla');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (404,'BOURNANE','Abdennour','1972-02-09','Bouzeria','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (406,'BEN','SAFI','1962-04-24','el harrache','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (425,'DERBAL','Samir','1964-03-08','Constantine','Constantine');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (426,'AKOUIRADJEMOU','Lies','1966-03-02','BAB EL OUED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (428,'DAOUD','Djilali','1955-05-27','SOUIDANIA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (429,'BABES','Mohamed','1971-09-12','guelma','Guelma');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (434,'ABBAS','Farouk','1974-08-23','BIRTOUTA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (438,'BENDERRADJI','Boualem','1961-07-16','Mohamed belouizdad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (439,'BOUDEHANE','Mahfoud','1969-01-11','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (448,'BOUMAZA','Nasr','1958-07-27','Blida','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (457,'DAMIR','Amar','1954-09-21','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (465,'MISSAOUI','Abdelghani','1976-10-06','Rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (466,'HAB','Mourad','1973-09-27','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (468,'BENREJDAL','Aissam','1975-07-22','Bab Elouad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (472,'MOKRANI','Abdelhalim','1965-06-20','BAB EL OUED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (481,'NEKA','M hamed','1956-10-06','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (487,'SLIMANI','Redouane','1969-09-09','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (488,'SEDDIKI','Mohamed','1957-06-06','Alger centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (493,'ATTIL','Mustapha','1983-03-25','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (495,'ABDOUN','Boudjema','1977-05-16','STAOUELI','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (523,'DRAOUCHE','Ahmed','1978-05-29','HUSSEIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (524,'OUNNAR','Rachid','1970-09-29','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (539,'HAMMOUDA','Yacine','1979-05-13','DOUIRA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (543,'IHAMMICHENE','Abderrezak','1963-04-11','Sidi Mhamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (558,'HANSAL','Kamel','1972-05-16','Bordj El Kiffan','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (568,'RAHIM','Youcef','1981-10-14','HUSSEIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (575,'KEMACHE','Abderezak','1971-09-24','BIRKHADEM','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (584,'SAHRAOUI','Seddik','1959-03-20','Alger Centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (599,'BENABID','Mustapha','1958-02-17','B.BOU  ARRERIDJ','B.B.Arréridj');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (603,'DAGHICH','Ahcene','1972-03-22','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (609,'BENABID','Djamel','1959-12-28','B.BOU  ARRERIDJ','B.B.Arréridj');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (610,'AMOURA','Mohamed','1998-03-03','EL MOURADIA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (611,'MENNOUR','Kamel','1965-03-06','Birkhadem','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (616,'LAZREG','Nacer','1973-06-13','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (618,'GHOMRASSI','Mehdi','1982-07-14','EL.BIAR','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (619,'TAHIRI','Mustapha','1953-08-24','Alger centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (625,'BOUBETRA','Mouloud','1977-03-06','BIR MOURAD RAIS','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (626,'BENACEUR','Mohamed','1988-02-08','Hammadi','Boumerdés');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (638,'SEBA','Reda','1965-06-24','kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (641,'BENAZIZ','Abdesselam','1976-10-16','EL-HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (648,'ZAHAF','Ahmed','1985-12-29','EL-HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (649,'KHERBA','Abdallah','1975-10-07','kolea','Tipaza');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (651,'GUELLIL','Abdelhak','1967-09-02','millia','Jijel');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (655,'BOUHADJA','Mehdi','1990-05-12','CHEBLI','Blida');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (656,'LAKSAS','Amar','1971-06-10','BAB EL OUED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (659,'ALOUI','Abderrahmane','1993-07-01','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (661,'MAKHLOUFI','Amine','1985-09-09','bouismail','Tipaza');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (663,'AZRAINE','Abdelkader','1988-09-17','BENI  KSILA','Béjaïa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (669,'ZAOUI','Boualem','1961-12-04','hussein day','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (670,'AIT-SEDDIK','Tahar','1954-04-12','FRIHA','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (671,'BACHAR','Toufik','1968-06-22','HUSSEIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (672,'KHODJA','Hachemi','1984-01-12','BARAKI','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (674,'BENNOUI','Amor','1956-03-24','RAS EL OYOUNE','Batna');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (675,'BELKIF','Hichem','1994-09-25','ZERALDA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (676,'RIHI','Mouloud','1969-06-03','sidi m hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (678,'ZEGHIDOUR','Ahmed','1985-07-02','Hussein Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (679,'HAMIDI','Moustapha','1983-01-05','ZERALDA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (688,'SAHRAOUI','Mohamed','1991-02-17','Ain taya','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (689,'RAI','Belkacem','1959-01-01','JEWAB','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (707,'IDJELLIDAINE','Salim','1979-06-30','AIN BENIAN','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (717,'LAKROUM','Sid','1982-01-13','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (720,'BELKHEIR','Mehdi','1984-11-19','beb el ouad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (721,'SMAALLAH','Djamel','1984-08-21','Douera','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (735,'BELDJELLA','Djilali','1950-10-03','HUSSEIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (736,'MEHMEL','Samir','1983-04-05','HADJOUT','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (738,'NEZALI','Ali','1966-10-22','DEOUIRA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (741,'MANSOURI','Okba','1988-06-05','alger centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (751,'ZEKRI','Ahmed','1964-03-22','EL HARRACHE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (761,'REKKACHE','Ahmed','1964-03-26','Bordj El Kiffan','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (765,'BOUSSAA','Mohamed','1968-10-26','Bab el oued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (767,'TELDJOUNE','Mohamed','1986-10-20','Rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (771,'BELAKHDAR','Othmane','1984-08-06','Beni Slimane','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (773,'GRICHE','Ahmed','1965-01-19','BORDJ EL KIFFAN','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (792,'BENRABAH','Djamel','1966-01-16','Dar el beida','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (802,'SAADI','Ahmed','1961-06-25','El-harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (818,'RIACHE','Ihssan','1983-03-24','Hussein-Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (825,'GARROUCHE','Abdelaziz','1974-03-21','harech','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (827,'KHEBOUR','Saadi','1976-02-25','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (829,'BENBOUTELDJA','Mohamed','1963-03-27','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (834,'GAAGA','Foudil','1975-04-14','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (837,'ABIDAT','Mouloud','1972-05-03','douera','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (838,'HACHEMI','Ahmed','1977-05-16','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (839,'LIASSINE','Mohamed','1974-09-18','MOHAMES BELOUAZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (840,'BOUTNAF','Adlane','1984-02-23','HOUSSIN DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (841,'KADI','Nasser','1961-02-24','bab eloued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (843,'SELAMA','Noureddine','1971-01-24','SIDI MHAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (845,'METICHE','Farid','1972-01-22','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (851,'LICIR','Meziane','1977-10-13','Sidi Moussa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (856,'BOUZIANI','Rachid','1982-07-09','hussein dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (857,'BOUIKNI','Samir','1981-08-21','DALI  -BRAHIM','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (858,'MALKI','Hocine','1967-04-25','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (863,'DJABRI','Mohamed','1977-11-21','hussein-dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (865,'RILI','Arab','1958-04-23','TIGHLIT','Béjaïa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (871,'MAMMAR','CHAOUCH','1965-09-05','douera','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (872,'OUGAOUA','Mustapha','1965-03-19','MOHAMED BELOUIZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (877,'BERRAHMA','Mahmoud','1982-05-30','alger centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (881,'AISSI','Sofiane','1973-08-13','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (883,'LOUAFI','Nacer','1979-09-10','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (885,'BENBOUTELDJA','Sadek','1966-01-18','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (888,'DERRARI','Hamza','1984-04-04','ALGER  CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (892,'RIACHE','Mahfoud','1984-08-15','Baraki','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (893,'NEBBOU','Billel','1995-06-28','Hussein-Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (897,'MAROC','Youcef','1961-12-31','MOHAMED BELOUIZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (898,'SERHANE','Mohamed','1972-09-12','med belouazedad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (900,'SAHRAOUI','Sid','1987-04-16','SOUR EL GHOZZLEN','Bouira');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (915,'BENMEHIRISSE','Bachir','1964-07-02','CASBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (917,'GUERNANE','Mohamed','1966-01-21','beo','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (919,'TADJINE','Nabil','1971-04-20','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (926,'BOUBRAOUAT','Rabah','1987-07-27','Khemis elkhechena','Boumerdés');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (944,'MESSADI','Abdelaziz','1968-02-18','Alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (948,'FERRADJI','Mohammed','1951-06-18','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (956,'HAMIDI','Mokhtar','1980-02-12','bouzareah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (958,'ALI','MOUSSA','1974-08-14','Bologhine','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (960,'MAAMRI','Ryad','1980-03-25','EL BIAR','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (962,'BANOUH','Mourad','1988-03-03','SAHARIDJ','Bouira');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (979,'BEZZAOUYA','Lotfi','1985-08-21','rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (993,'SAADOU','Kamel','1966-02-01','Cheraga','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (994,'SLIMANI','Azzeddine','1960-05-01','CHLEF','Chlef');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1002,'ALI','Nassim','1981-11-08','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1009,'ROUAM','Mebarek','1975-05-11','medea','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1010,'BANAT','Abdelhamid','1957-08-20','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1013,'ESSAIDI','Zineddine','1987-06-16','médéa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1014,'BELKACEMI','Mohamed','1973-07-19','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1029,'CHERGUI','Noureddine','1969-07-31','H.DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1034,'AMOURA','Boualem','1963-06-04','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1036,'DEFFAF','Abdelhamid','1983-06-26','REGHAIA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1039,'BESSAOUD','Noureddine','1972-03-07','Bab el Oued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1051,'HAZEM','Mohammed','1971-02-22','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1054,'MERDJ','Mohamed','1982-11-24','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1055,'CHERGUI','Abdelhak','1992-02-21','reghaia','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1056,'BELGHOUL','Rabei','1960-02-05','CASBAH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1057,'BADANI','Athmane','1971-04-27','Ghenzat','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1058,'DJABALLAH','Mourad','1982-10-02','Alger Centre','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1059,'BELHADJI','Lyacine','1979-04-08','El Harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1061,'ZINAI','Djamél','1994-11-27','Alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1062,'AIT','AIDER','1963-03-31','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1063,'BENMEDDAH','Brahim','1974-10-10','CHERAGA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1064,'SIDI','YAHYA','1961-07-22','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1068,'ALILOUCHE','M hamed','1992-04-23','bourouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1070,'RABIA','Amine','1983-07-01','Ain taya','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1075,'BELHABIB','Nabil','1974-04-22','Sidi M hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1081,'MOKHTARI','Mouhoub','1982-02-08','B M R','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1082,'BOUAMRA','Mohamed','1974-01-01','Aziaz','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1089,'BESSOU','Yacine','1980-02-16','Hussein Dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1093,'AKKOURT','Samir','1991-07-07','HAMMAMET','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1096,'MECHKOUR','Salim','1966-09-29','Sidi M hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1099,'OUDJANE','Djamal','1969-12-19','cheraga','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1107,'DEHRIB','Abdelhalim','1964-09-23','STAOUELI','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1116,'BELAIDI','Azeddine','1966-08-21','bouira','Bouira');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1120,'HADDAD','Hocine','1977-11-20','BEO','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1124,'ZEKOUKI','Yazid','1962-06-23','meftah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1133,'HADJ','KACI','1984-09-22','HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1135,'BOUTARENE','Khayreddine','1994-07-05','el attaf','Ain Defla');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1137,'RAHAL','Mohamed','1993-09-22','BENI MESSOUS','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1143,'SI','AMER','1988-04-02','Ain el hammam','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1150,'FAROUKHI','Ali','1971-04-03','MED  BELOUIZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1161,'MEHAMHA','Cherif','1988-01-28','H. Déy','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1163,'IKEN','Hicham','1987-10-29','hammamet','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1179,'BENDADA','Azziz','1982-08-01','CONSTANTINE','Constantine');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1186,'MOUSSAOUI','Hani','1997-03-30','setif','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1191,'YOUSFI','Chafik','1965-02-05','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1192,'NADJI','Hakim','1969-10-17','Belouizdad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1196,'MAREF','Mounir','1984-01-25','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1199,'SOUILAH','Fouad','1973-07-09','El harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1201,'LAZEGHED','Fateh','1986-03-17','CASBAH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1206,'CHEKARI','Mustapha','1984-12-26','Rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1212,'HAMICHE','Mohamed','1982-11-23','D. E. B','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1213,'MECHTA','Farid','1973-01-07','Rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1214,'HAMADI','Moussa','1993-12-07','MEDIA','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1215,'HALOUANE','Ali','1960-04-15','THENIA','Boumerdés');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1216,'BOUHALASSI','Ahmed','1958-06-18','AIN EL BEIDA','Oum El Bouaghi');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1217,'BOUCHELGHOUM','Zine','1995-02-12','CHNIGUEL','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1218,'HAMMOUNE','Brahim','1994-05-06','Azeffoun','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1220,'GANA','Smail','1977-02-16','118106467','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1223,'MOUIADI','Mohamed','1976-07-04','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1224,'BELMADANI','Rabie','1980-11-19','Sidi M hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1227,'TADJA','Said','1980-11-13','E','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1228,'SIDIRA','Sofiane','1974-06-15','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1229,'FERRAGUI','Sidali','1970-03-06','Douira','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1231,'LEHARANI','Mohamed','1949-02-14','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1232,'MEHAIGUENI','Djamel','1995-09-17','AZABA','Skikda');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1233,'LAKHDAR','CHAOUCH','1994-01-04','ELBIAR','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1234,'MAOUCHE','Ali','1971-03-18','elharrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1235,'MEDJADBA','Salah','1988-07-20','BNI AZIZE','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1236,'MAAMRI','Zakaria','1991-12-12','Bab El Oued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1237,'BENKACI','Malek','1954-09-10','TIZI OUZOU','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1238,'KRAGHEL','Toufik','1968-01-01','Sidi Ahmed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1241,'LAKHLEF','Djamal','1966-08-16','BELOUIZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1243,'BENAIFA','Mohamed','1983-06-14','Bouzaria','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1245,'MEFTI','Oussama','1999-06-14','H-DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1248,'BELHOUT','Abdelaid','1993-10-11','beo','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1249,'BELLAL','Hamza','1996-07-30','bablawad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1250,'BOUZIDI','Abdelkader','1981-01-25','MEDEA','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1251,'DERBACI','Mouloud','1977-03-02','bologhine','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1252,'OUGGADI','Ali','1987-10-15','BENI MESSOUS','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1253,'GACEM','Tayeb','1972-04-05','Chebli','Blida');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1254,'AMEUR','Naseredine','1963-06-20','EUCALUPTUS','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1256,'BOUROUIS','Reda','1975-10-18','DOUERA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1257,'DJOUDI','Adnane','1975-12-04','MOHAMED BELOUIZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1258,'KAMEL','Brahim','1970-09-06','sour  el ghzlane','Bouira');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1259,'GHOUL','Abdelkrim','1994-09-28','ANNABA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1260,'MOSTEFAOUI','Hamza','1981-07-30','Kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1261,'BELACEL','Mohamed','1989-12-10','HUSSINE DEY','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1262,'BOUMERFEG','Nabil','1962-09-15','SETIF','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1263,'ZANANE','Ahmed','1975-01-28','Koléa','Tipaza');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1264,'BENKERROUCHE','Mohammed','1962-08-19','Ouled Moussa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1265,'BOUKOURA','Mahmoud','1965-08-09','Bab eloued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1268,'BENLARIBI','Ameur','1982-04-11','AIN BOUCIF','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1269,'BENHAGOUGA','Merouane','1976-01-31','hocine dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1270,'CHAIB','DRAA','1986-01-16','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1271,'MAICHI','Reda','1975-08-28','Harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1272,'DJEBROUNI','Mohamed','1971-04-26','Bordj El Kiffan','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1273,'EL','','1953-04-19','EL MELSSA','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1274,'BOUDJEMA','Samir','1980-02-27','bouzeréa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1275,'BRAHIMI','Abdelkader','1975-01-19','Ain Boucif','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1276,'SADALLAH','Mourad','1981-02-25','ELHARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1277,'MENAD','Karim','1987-09-05','Tizi ouzou','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1278,'GHOUILA','Ammar','1980-05-21','Jijel','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1279,'BOUGUERRA','Med','1987-02-26','CASBAH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1280,'MEZRAI','Abdelillah','1995-07-18','Remchi','Tlemcen');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1282,'HAOUFAF','Azzedine','1962-02-11','EL harrach','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1283,'ANDALOUSSI','Abdelkrim','1985-07-04','Bab El Oued','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1284,'MERZOUG','Miloud','1967-06-08','chéraga','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1285,'LATRI','Toufik','1968-10-20','SIDI MHAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1286,'CHEBTA','Ammar','1994-03-10','Fardjioua','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1287,'BESTANI','Yahia','1976-10-17','staoueli','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1288,'MANSLI','Hamid','1958-05-11','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1289,'TOUZI','Yacine','1992-05-17','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1290,'ARAFA','Larbi','1976-01-17','chlef','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1293,'HALLAS','Abdelhamid','1971-07-14','tesmsilt','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1294,'BENTAMA','Djamel','1966-04-04','SIDI MED BEN ALI','Relizane');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1296,'OUCHEN','Mohamed','1972-01-26','el biar','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1297,'BELKSIR','Tahar','1960-01-07','HARACHE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1298,'LEKIRED','Mohamed','1987-03-18','EL EULMA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1299,'DEROUICHE','Faycal','1994-11-18','BENI MESSOSE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1300,'BENBAYA','Fouad','1974-01-07','bologhine','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1301,'MAOUCHE','M hamed','1968-02-18','Hussein dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1302,'NANOUCHE','Kamel','1964-01-09','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1304,'ZAIOU','Faycel','1994-08-10','Reghaia','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1305,'NEGHLI','Hakim','1987-01-05','TIZI OUZOU','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1306,'DRAOUI','Khaled','1992-08-17','Reghaia','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1307,'MOHAMED','Lekired','1987-03-18','EL ALMA','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1308,'BENSALEM','Cherif','1988-03-08','Alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1309,'MOUSSAOUI','Said','1991-05-18','sidi m hamed','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1310,'MEZIANI','Toufik','1987-12-03','Bouskene','Médéa');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1311,'NOUACER','Djamal','1955-04-02','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1312,'BOUKEMOUCHE','Abdelouahab','1970-01-28','Hussein dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1313,'FEZZAI','Mustapha','1953-12-04','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1314,'BENCHERNIN','Hocine','1978-01-11','Djaafra','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1315,'BENHAGOUGA','Raouf','1978-02-15','hussin day','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1316,'BEDOUD','Mohamed','1965-07-26','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1317,'MIZIANI','Azeddine','1969-04-22','MOHAMED BELOUZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1318,'LAROUM','Mohamed','1989-05-28','BENI MESSOSE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1319,'BEN','MAHDJOUB','1981-04-06','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1320,'OULAK','Adel','1996-11-20','hussein dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1322,'ALBANE','Nourreddine','1963-04-22','ALGER','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1323,'MEDDAH','Mohamed','1970-09-16','BIRTOUTA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1324,'OULD','MOHAMED','1987-05-09','djelfa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1326,'BENOBEIDALLAH','Abderrezak','1969-04-24','zeralda','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1327,'ALOUI','Fouaz','1978-06-13','BELOUEZDAD','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1328,'LARABI','Mohamed','1973-10-13','SIDI M HAMED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1330,'DEGHICHE','Rafik','1983-10-01','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1331,'ABDESLAM','Mohand','1995-09-20','Ain El Hammam','Tizi-Ouzou');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1332,'BOUTICHE','Mohamed','1998-08-22','sétif','Sétif');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1333,'MELKAOUI','Slimane','1992-12-19','el-harache','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1334,'BEKHTOUCHI','Mohamed','1996-09-01','CHLEF','Chlef');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1335,'HATTOU','Mohamed','2002-01-12','BENI MESSOUS','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1337,'MERADI','Ali','1964-01-23','Med Belouezdad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1338,'LALI','Khaled','1995-01-27','SIDI ABED','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1339,'TOUBRINET','Mourad','1974-12-30','kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1340,'KHERABI','Fares','1992-01-22','ROUIBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1341,'GHARBI','Lyas','1974-03-01','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1342,'BENSEGHIR','Mehdi','1971-07-07','Hussei-dey','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1343,'KHENIFI','Sid','1982-05-15','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1344,'ABBAS','Ali','1983-02-15','BOUFARIK','Blida');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1346,'MEGHARI','Mourad','1967-08-08','ORAN','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1347,'BOUBAAYA','Amar','1965-11-14','KOUBA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1348,'MERSELLEM','Abdelkader','1976-03-09','ain defla','Ain Defla');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1349,'AKRICH','Mohamed','1961-07-02','Mohamed Belouizdad','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1350,'AIT','ATHMANE.','1988-07-31','Djasr Kasentina','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1351,'SALMA','Issam','1992-08-29','tbessa','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1352,'BEN','SADOUNI','1984-03-10','AIN TAYA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1353,'ELZAANINE','Salam','1999-01-12','kouba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1354,'CHAKALI','Ahmed','1974-03-07','EL HARRACH','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1355,'BAZIZ','Sofiane','1980-01-16','bouzaerah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1356,'CHABLAOUI','Djelloul','1965-01-01','MEDEA','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1358,'LADDI','Kheireddine','1996-10-11','BIR KHADEM','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1359,'HANTOUT','Riadh','1980-03-16','rouiba','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1360,'BEN','ALI','1979-12-05','ALGER CENTRE','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1363,'MILOUDI','Fateh','2000-02-13','Zeralda','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1364,'TAIBI','Mohamed','2002-03-08','El abier','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1365,'NOUMRI','Karim','1993-07-13','Zeralda','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1366,'BENHAIK','Youcef','1997-01-31','douira','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1368,'MECHRI','Mohamed','1961-02-15','alger','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1369,'SAADOUNE','Mohamed','1981-05-31','bouzarreah','Alger');
INSERT INTO Entraineur(idEntraineur,nom,prenom,dateNaissance,lieuNaissance,wilayaNaissance) VALUES (1371,'REHIM','Guealia','1982-09-03','Elharrach','Alger');
