INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (0,'neant');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (1,'Magri moncef');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (2,'rabia Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (3,'Aktouf');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (4,'SAIDANI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (5,'ayache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (6,'BOURAHLA Boualem');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (7,'souilah oubiada');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (8,'Ayache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (9,'Ait chaouche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (10,'Mr Cheraitia');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (11,'charour smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (12,'toubal fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (13,'boukhedache hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (14,'belhout');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (15,'aktouf');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (16,'rabia yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (17,'ZADI Sofiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (18,'Benounnas zin eddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (19,'Cher our ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (20,'Zabati Nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (21,'belhout abdel aid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (22,'cherour ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (23,'ZAADI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (24,'ait chaouche Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (25,'bouaamra rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (26,'debouri kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (27,'ayache karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (28,'BENKHEDDACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (29,'BOUHAMADI Ibrahim Fouad');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (30,'Bouamra rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (31,'Aktouf Houdaifa Salim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (32,'maziri amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (33,'Zadi sofiene');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (34,'bouamra rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (35,'magri moncef');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (36,'DDJOUDI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (37,'Zabati nadjib hossam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (38,'Mr rabia');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (39,'Aktouf Houdaifa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (40,'Maziri amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (41,'HADJRES');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (42,'ZABATI NADJIB');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (43,'Mr zadi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (44,'kermiche yasser');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (45,'TOUBAL. FATEH');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (46,'zabati nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (47,'DEBOURI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (48,'Belhout abdelaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (49,'Berrani Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (50,'MAGRI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (51,'Boukheddache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (52,'baklioui moussa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (53,'SOUILAH OBAIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (54,'Hadjeres');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (55,'lelouchi sid ahmed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (56,'LELLOUCHI Sid Ahmed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (57,'Mr debouri kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (58,'cherour smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (59,'ait chaouch khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (60,'belhout belaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (61,'DJOUDI Zakaria');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (62,'Hadjres Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (63,'Charchour islam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (64,'Aktouf oudeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (65,'BOUAMRA RACHID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (66,'ZABATI Nadjid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (67,'Cherour ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (68,'Belhout laid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (69,'Mr Maziri Amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (70,'Ait chaouche khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (71,'Rabia yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (72,'BELHOUT');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (73,'BENOUANES ZINEDIN');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (74,'Mr Zadi Sofiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (75,'AYACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (76,'Mr Ait Chaouche khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (77,'selami fares');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (78,'ZABATI Nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (79,'TOUBAL Fetah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (80,'BENOUNAS ZINEDDINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (81,'Ben serhane Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (82,'Boukhedache Hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (83,'DEBOURI KAMEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (84,'BADACHE ABDELKARIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (85,'CHEROUR ISMAIL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (86,'benserhane akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (87,'SAHLI LAMINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (88,'souilah oubiba');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (89,'saidani hossam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (90,'Ayache karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (91,'Sahli lamine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (92,'SELLAMI Fares');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (93,'Cherour');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (94,'Ait Chaouche Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (95,'Mr Benounas Zineddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (96,'OSMANI FAYSAL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (97,'AYACHE  Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (98,'Maziri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (99,'Mr Ait Chaouche Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (100,'Maziri Amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (101,'Mr Hadjeres Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (102,'Toubal Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (103,'Benserhane Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (104,'MrAyache Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (105,'Boukhedacha Ahmed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (106,'berani');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (107,'Benelam Anis');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (108,'Mr djoudi Zaki');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (109,'RABIA. YACINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (110,'BOUKHEDDACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (111,'RAbia yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (112,'Amar Khodja Ryad');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (113,'HAJRAS FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (114,'SENNI Mounir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (115,'Mr Benmira Abderezak');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (116,'Chihaoui El Hadj');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (117,'Mr Cherour Smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (118,'ZABATI Abderraouf');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (119,'benmira abderezak');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (120,'Kouadri Mohamed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (121,'TOUBAL  Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (122,'MOUDJEB ANIS');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (123,'berrani');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (124,'SERDJANE Massinissa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (125,'BOUKHEDACHE Hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (126,'AIT CHAOUCH KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (127,'Mr Safsaf Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (128,'hadjres farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (129,'Mameri Zakaria');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (130,'Rabia Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (131,'Souilah oubaida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (132,'Ayache Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (133,'HADDOUCHE Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (134,'ZAIDI Abdelkrim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (135,'boukhedache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (136,'ait chaouche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (137,'zadi Sofiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (138,'HADJERAS FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (139,'Belhoute');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (140,'benounnas');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (141,'SOUILAH AOUEBIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (142,'hadjres');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (143,'Mr cheraitia');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (144,'cherour');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (145,'Souilah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (146,'Ait chaouche.');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (147,'Zaidi Sofiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (148,'MAGRI MONCEF');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (149,'chraitia billal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (150,'Aktouf houdaifa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (151,'BENHAMADI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (152,'BOUKHEDACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (153,'cheraitia');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (154,'TOUBAL  FATEH');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (155,'SOUILAH');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (156,'CHERROUR  ISMAIL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (157,'AIT CHAOUCHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (158,'Badache abdelkrim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (159,'aktouf islam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (160,'Zabati nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (161,'Debouri Kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (162,'Rabia');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (163,'CHEROUR');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (164,'Mr ayache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (165,'TOUBAL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (166,'boukhedach hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (167,'Debouri kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (168,'Cheraitia bilel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (169,'Mr boukhedache hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (170,'HADJRAS FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (171,'Ait chaouche Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (172,'Belhout');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (173,'BELHOUT ABDELAID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (174,'Ait chaouch khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (175,'Bouamra Rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (176,'HADJERAS. FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (177,'MAGRI. MONCEF');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (178,'Mr Sahli Lamine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (179,'Mr Toubal Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (180,'Cheraitia Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (181,'Mr Hadjres Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (182,'Zadi sofienne');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (183,'zabat nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (184,'Toubal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (185,'AKTOUF HOUDAIFA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (186,'CHEROUR Smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (187,'CHEROUR SMAIL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (188,'AYACHE KARIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (189,'HADJRES Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (190,'RABIA YACINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (191,'MAZIRI AMIR');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (192,'HADJRES FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (193,'CHERATIA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (194,'SAHLI Amine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (195,'BENOUNNAS ZINEDDINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (196,'RABIA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (197,'Cherour Ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (198,'BELHOUT LAID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (199,'Mr Belhout Belaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (200,'boukhedeche hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (201,'AYACHE Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (202,'BADACHE AKRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (203,'Mr Lelouchi Sid Ahmed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (204,'bensarhar');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (205,'toubal Fatah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (206,'Ait Chaouch');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (207,'Berani Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (208,'Mr Boukhedache Hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (209,'AIT CHAOUCH. Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (210,'Sahli');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (211,'Mr Ayache Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (212,'Mr Boudjellal Fouad');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (213,'Cherour Smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (214,'Chalabi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (215,'MAZIRI Amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (216,'djoudi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (217,'Souilah Obeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (218,'Cherour smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (219,'Souilah Oubaida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (220,'HADJERAS  Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (221,'OSMANI FAYCEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (222,'mazeri amir');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (223,'Mr Serdjane Massinissa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (224,'Bénmira Abderezak');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (225,'toubal  fatah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (226,'Mr Bensarhane Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (227,'ZADI SOUFIANE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (228,'CHEROUR  Ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (229,'Debouri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (230,'BOUKHDACHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (231,'TOUBAL FATAH');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (232,'Bouamra');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (233,'MEGUELLATI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (234,'MAZIRI  AMIR');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (235,'HADJERAS Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (236,'RABIA  YACINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (237,'SAIDANI Houssam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (238,'boukhaddache hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (239,'AKTOUF');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (240,'AIT CHAOUCH Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (241,'boumra Rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (242,'AYACHE  KARIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (243,'CHERAITIA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (244,'Rabi yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (245,'AIT CHAOUCH. KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (246,'Mr souilah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (247,'TOUBAL Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (248,'MMagri moncef');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (249,'Boukhadache Hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (250,'badache a/karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (251,'BOUKHADDCHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (252,'CHERATIA BELAL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (253,'Mr ait chaouche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (254,'Hadjress Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (255,'BADACHE A_KRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (256,'BERRANI. AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (257,'TOUBAL FATEH');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (258,'Mr hadjres');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (259,'BOUAMRA Rachid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (260,'Rabeya yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (261,'BOUKHADDACHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (262,'BADACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (263,'CHEROUR Ismail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (264,'Badache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (265,'Mr Cheraitia Billal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (266,'HADJERES Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (267,'Mr Guermache Mahdi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (268,'Cheraitia bilal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (269,'AIT CHAOUCH  KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (270,'BOUKHEDACHE  HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (271,'goubi  bilel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (272,'badache abdelkrim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (273,'Mr hadjeres Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (274,'BERRANI AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (275,'debbouri kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (276,'BENSERHANE Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (277,'HADJERES FAROUK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (278,'BOUDJELLAL FOUAD');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (279,'CHEROUR  ISMAIL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (280,'BOUKHEDACHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (281,'toubal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (282,'HADJERAS. Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (283,'CHERROUR ISMAIL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (284,'TOUBAL Fatah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (285,'AIT CHAOUCHE Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (286,'Mr Rabia Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (287,'benmira');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (288,'HADDOUCHE WALID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (289,'Hadjeras');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (290,'CHERAITIA  BILEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (291,'BERANI AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (292,'Haddouche Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (293,'BOUKHEDACHE. HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (294,'Badache Abdelkrim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (295,'SAIDANI Housem');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (296,'SELLAMI FARES');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (297,'Mr haddouche walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (298,'SAiDANi HOUSSAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (299,'KERMCHE Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (300,'BOUKHEDACHE HHAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (301,'HADOUCHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (302,'SADAOUI Rabah Adlane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (303,'BADACHE  ABDELKRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (304,'MAGRI Moncef');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (305,'GOUBI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (306,'souilah oubeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (307,'BADACHE A/KRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (308,'SAIDANI HOUSSEM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (309,'SELLAMI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (310,'HADDOUCHE  WALID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (311,'LOUGHRAIEB Abdelatif');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (312,'sadouni  soufiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (313,'mengalati  hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (314,'haddouche walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (315,'SOUILAH OUBAIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (316,'BOUKHADACHE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (317,'Mr Zabati Nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (318,'maziri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (319,'Benserhane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (320,'Benounas');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (321,'toubal fatah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (322,'KERMICHE Yasser');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (323,'BOUKHEDDACHE  HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (324,'Mr Souilah Oubaida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (325,'zabati  nadjib');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (326,'SAIDANI HOUSSAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (327,'BADACHE  A/KRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (328,'BENSERHANE  AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (329,'hadjeras');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (330,'GOUBI Bilal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (331,'BOUKHADACHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (332,'HADOUCHE Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (333,'SELLAMI. Fares');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (334,'BADACHE ABDELKRIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (335,'GOUBI Blilal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (336,'SOUILAH OBEIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (337,'SAADAOUI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (338,'TOUBAL. Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (339,'sellami feras');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (340,'Mr Bekkou Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (341,'Guermache mahdi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (342,'hadjeras Farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (343,'BEKKOU YACINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (344,'Toubal fatah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (345,'Baklioui moussa');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (346,'MENGUELLATI  Hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (347,'ALLOUNE Islem');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (348,'debouri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (349,'Brnaouda aziz');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (350,'sellami fares');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (351,'Menguellati Hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (352,'GouBi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (353,'souilah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (354,'SOUILAH  OBEIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (355,'Debouri Kamal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (356,'Bouhamadi Ibrahim fouad');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (357,'Benounes');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (358,'MENGUELLATI  HAMID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (359,'menguelati  hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (360,'SAHLI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (361,'HADOUCHE WALID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (362,'hadouche Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (363,'GUERNANE Toufik');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (364,'benounes sifeddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (365,'souilah oubida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (366,'BENOUNAS');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (367,'Saidani houssam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (368,'Goubi Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (369,'DABOURI KAMEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (370,'Hadjres farouk');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (371,'AIT CHAOUCHE KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (372,'saadaoui adlen');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (373,'SIADANI OUSSAMA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (374,'Boukhdache Hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (375,'SAHLI  LAMINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (376,'Haddouche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (377,'Mr Benserhane Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (378,'ABANE Youcef');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (379,'saadaoui rabah');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (380,'souilah obeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (381,'SAHLI  AMINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (382,'cherrour smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (383,'SOUILAH Obaida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (384,'Mr Souilah Obeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (385,'BENSERHANE AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (386,'GOUBI Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (387,'HADDOUCHE  Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (388,'Mr Menguellati Hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (389,'AIT CHAOUCHE  Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (390,'GUERNANE Tewfiq');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (391,'BOUKHDACHE HAMAZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (392,'souilah oubaiada');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (393,'rachid bouamra');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (394,'Benouda');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (395,'MENGUELLATI Hamid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (396,'belhoute abdelaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (397,'goubi Bilel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (398,'baddache abdelkarim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (399,'bensarhane akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (400,'Benaouda mohamed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (401,'Benaouda');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (402,'DEBBOURI');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (403,'Saadaoui');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (404,'BENOUNNAS Zineddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (405,'KERMICHE YASER');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (406,'Mr Saidani Houssem');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (407,'Belhout balaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (408,'BENSERHANE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (409,'Dabouri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (410,'ben sarhen Akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (411,'BENAMOR');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (412,'BELHOUT  ABDELAID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (413,'MEZAOUR Islam Badis');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (414,'benounes zin edine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (415,'Souilah oubida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (416,'AYACHE. Karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (417,'GOUBI BILAL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (418,'GOUBI  BILLEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (419,'cherour Smail');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (420,'Mr Ait Chzouche Khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (421,'Souilah Oubeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (422,'SUILAH OUBAIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (423,'BENOUNNAS Zine eddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (424,'goubi billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (425,'SOUILAH OUBIDA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (426,'DEBOUR KAMEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (427,'Saidani');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (428,'Abdou Abderrahim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (429,'benserhana akram');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (430,'ammi abdenour');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (431,'Mr goubi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (432,'benounnas zineddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (433,'cheraitia bilel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (434,'mzaour islam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (435,'Benaouda Med');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (436,'Benouannas Zineddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (437,'zadi Soufiane');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (438,'benaouda mohamed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (439,'goubi bilel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (440,'BOUKHEBACHE HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (441,'GOUBI billal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (442,'saidani');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (443,'ait chaouache khaled');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (444,'AIT CHAOUACHE KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (445,'Toubal fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (446,'Boukhedache hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (447,'saidani ousama');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (448,'belhout abdelaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (449,'CHERAITIA  Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (450,'cheraitia bilal');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (451,'cheraitia billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (452,'boukheddeche  hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (453,'Ait Chaouche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (454,'Guernane Toufik');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (455,'Gobi Billel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (456,'ait  chaouache');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (457,'ZAATOUCHI Adel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (458,'GUERNANE TOUFIK');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (459,'Ait chaouche hamza');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (460,'Souileh Oubeida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (461,'BENSARHANE AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (462,'benounes');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (463,'BENSARHAN AKRAM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (464,'AIT CHAOUCH  HAMZA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (465,'BELHOUT ABD EL AID');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (466,'BENOUNES ZINE EDDINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (467,'Guernane toufik');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (468,'ammi abdelnour');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (469,'mekid aymen');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (470,'abdou');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (471,'SOUILAH OUBIADA');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (472,'Saidani Houssem');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (473,'LEZGHED Fateh');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (474,'GOUBI BILLEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (475,'BADACHE  abel karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (476,'BELHOUT Abdelaid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (477,'RABIA yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (478,'DEBOURI Kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (479,'SAADAOUI Rabah Adlene');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (480,'ZABATI  NADJIB');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (481,'BENAOUDA MOHAMED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (482,'souilah oubaida');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (483,'CHERAITIA BILLEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (484,'CHERAITIA. BILEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (485,'SAADAOUI. RABAH ADLANE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (486,'Saidani Houssam');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (487,'djebouri');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (488,'karmiche');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (489,'lazghed');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (490,'Bekkou Yacine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (491,'Sahli Amine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (492,'ayache  karim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (493,'Mr Haddouche Walid');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (494,'AKTOUF  HOUDAIFA SALIM');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (495,'LOUGHRIEB');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (496,'AIT/CHAOUCHE KHALED');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (497,'benounes med');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (498,'SAHLI AMINE');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (499,'HASSANI Louay');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (500,'Dabouri Kamel');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (501,'goubi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (502,'SAFSAF BILLEL');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (503,'Goubi');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (504,'ayache akrim');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (505,'belhout abdelied');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (506,'benounnas zin eddine');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (507,'benmessaoud');
INSERT INTO Arbitre(idArbitre,nomArbitre) VALUES (508,'Mr Djoudi Zaki');
