INSERT INTO Stade(idStade,nomStade) VALUES (0,'EL-MOKRANI -Ben Aknoun');
INSERT INTO Stade(idStade,nomStade) VALUES (1,'AIN BENIAN');
INSERT INTO Stade(idStade,nomStade) VALUES (2,'None');
INSERT INTO Stade(idStade,nomStade) VALUES (3,'OULED FAYET');
INSERT INTO Stade(idStade,nomStade) VALUES (4,'ZERALDA - ALI BENFADHA');
INSERT INTO Stade(idStade,nomStade) VALUES (5,'HYDRA');
INSERT INTO Stade(idStade,nomStade) VALUES (6,'BOLOGHINE');
INSERT INTO Stade(idStade,nomStade) VALUES (7,'BIRTOUTA');
INSERT INTO Stade(idStade,nomStade) VALUES (8,'EL-BIAR - IBRIR');
INSERT INTO Stade(idStade,nomStade) VALUES (9,'BENTALHA');
INSERT INTO Stade(idStade,nomStade) VALUES (10,'DELY BRAHIM');
INSERT INTO Stade(idStade,nomStade) VALUES (11,'STAOUELI');
INSERT INTO Stade(idStade,nomStade) VALUES (12,'EL-ACHOUR');
INSERT INTO Stade(idStade,nomStade) VALUES (13,'DOUERA');
INSERT INTO Stade(idStade,nomStade) VALUES (14,'1er Novembre');
INSERT INTO Stade(idStade,nomStade) VALUES (15,'BOUROUBA');
INSERT INTO Stade(idStade,nomStade) VALUES (16,'20 Août 1955');
INSERT INTO Stade(idStade,nomStade) VALUES (17,'KOUBA -Ben Haddad');
INSERT INTO Stade(idStade,nomStade) VALUES (18,'DJASR KACENTINA');
INSERT INTO Stade(idStade,nomStade) VALUES (19,'EL-HAMIZ');
INSERT INTO Stade(idStade,nomStade) VALUES (20,'BAB EZZOUAR');
INSERT INTO Stade(idStade,nomStade) VALUES (21,'OULED CHEBEL');
INSERT INTO Stade(idStade,nomStade) VALUES (22,'CAMP NORD - DAR EL-BEIDA');
INSERT INTO Stade(idStade,nomStade) VALUES (23,'HAI ENNASR');
INSERT INTO Stade(idStade,nomStade) VALUES (24,'AIN TAYA');
INSERT INTO Stade(idStade,nomStade) VALUES (25,'BORDJ EL-BAHRI');
INSERT INTO Stade(idStade,nomStade) VALUES (26,'REGHAIA');
INSERT INTO Stade(idStade,nomStade) VALUES (27,'BARAKI');
INSERT INTO Stade(idStade,nomStade) VALUES (28,'SIDI MOUSSA');
INSERT INTO Stade(idStade,nomStade) VALUES (29,'KHRAICIA');
INSERT INTO Stade(idStade,nomStade) VALUES (30,'MAHELMA');
INSERT INTO Stade(idStade,nomStade) VALUES (31,'BABA HASSEN');
